[package]
name = 'cardDuel'
version = '1.0.0'

[addresses]
# Testnet Address
duel = "b7037796ecd2a38dac52844a1aca3d002460d4d829550cd8adcce9c4e30e09ca"


[dependencies.AptosFramework]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = 'mainnet'
subdir = 'aptos-move/framework/aptos-framework'

[dependencies.AptosStdlib]
git = "https://github.com/aptos-labs/aptos-core.git"
subdir = "aptos-move/framework/aptos-stdlib"
rev = "mainnet"